
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahmoud
 */
public class SimpleNotePad extends javax.swing.JFrame {

    /**
     * Creates new form SimpleNotePad
     */
    private String path;
    private FileNameExtensionFilter filter;
    private String text ="", x;
    private FileReader fileRead;
    private FileWriter fileWrite;
    private BufferedReader fileIn;
    private BufferedWriter fileOut;
    private JFileChooser choose;                
    public SimpleNotePad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();
        aboutForm = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menu2 = new javax.swing.JPopupMenu();
        copyMenu2 = new javax.swing.JMenuItem();
        cutMenu2 = new javax.swing.JMenuItem();
        pasteMenu2 = new javax.swing.JMenuItem();
        selectAllMenu2 = new javax.swing.JMenuItem();
        exitDialog = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        dontSaveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        closeDialog = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        saveButton1 = new javax.swing.JButton();
        dontSaveButton1 = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        copyMenu = new javax.swing.JMenuItem();
        cutMenu = new javax.swing.JMenuItem();
        pasteMenu = new javax.swing.JMenuItem();
        selectAllMenu = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        aboutApp = new javax.swing.JMenuItem();

        aboutForm.setTitle("About Application");
        aboutForm.setAlwaysOnTop(true);
        aboutForm.setMaximumSize(new java.awt.Dimension(512, 270));
        aboutForm.setPreferredSize(new java.awt.Dimension(512, 270));
        aboutForm.setResizable(false);
        aboutForm.setSize(new java.awt.Dimension(512, 270));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Ver 0.1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Notepad");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Simple");

        jLabel4.setFont(new java.awt.Font("Utsaah", 3, 24)); // NOI18N
        jLabel4.setText("My");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Special thanks to:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Eng. Fady Samuel");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("By. Mahmoud Gamal");

        jLabel5.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel5.setText("http://www.mahmoudgamal.com");

        jLabel6.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        jLabel6.setText("http://www.github.com/mga599/mysimplenotepad");

        javax.swing.GroupLayout aboutFormLayout = new javax.swing.GroupLayout(aboutForm.getContentPane());
        aboutForm.getContentPane().setLayout(aboutFormLayout);
        aboutFormLayout.setHorizontalGroup(
            aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutFormLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(aboutFormLayout.createSequentialGroup()
                        .addGroup(aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aboutFormLayout.createSequentialGroup()
                                .addGroup(aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(aboutFormLayout.createSequentialGroup()
                                .addGroup(aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, aboutFormLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutFormLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(19, 19, 19)))))
                        .addContainerGap())))
        );
        aboutFormLayout.setVerticalGroup(
            aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutFormLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(aboutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(aboutFormLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        copyMenu2.setText("Copy");
        copyMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenu2ActionPerformed(evt);
            }
        });
        menu2.add(copyMenu2);

        cutMenu2.setText("Cut");
        cutMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenu2ActionPerformed(evt);
            }
        });
        menu2.add(cutMenu2);

        pasteMenu2.setText("Paste");
        pasteMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenu2ActionPerformed(evt);
            }
        });
        menu2.add(pasteMenu2);

        selectAllMenu2.setText("Select All");
        selectAllMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllMenu2ActionPerformed(evt);
            }
        });
        menu2.add(selectAllMenu2);

        exitDialog.setTitle("Exit");
        exitDialog.setMaximumSize(new java.awt.Dimension(400, 125));
        exitDialog.setPreferredSize(new java.awt.Dimension(400, 125));
        exitDialog.setResizable(false);
        exitDialog.setSize(new java.awt.Dimension(400, 125));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Do you want to save");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        dontSaveButton.setText("Don't save");
        dontSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontSaveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exitDialogLayout = new javax.swing.GroupLayout(exitDialog.getContentPane());
        exitDialog.getContentPane().setLayout(exitDialogLayout);
        exitDialogLayout.setHorizontalGroup(
            exitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exitDialogLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(exitDialogLayout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(87, 87, 87)
                        .addComponent(dontSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitDialogLayout.setVerticalGroup(
            exitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(exitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(dontSaveButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeDialog.setTitle("Exit");
        closeDialog.setMaximumSize(new java.awt.Dimension(400, 125));
        closeDialog.setPreferredSize(new java.awt.Dimension(400, 125));
        closeDialog.setResizable(false);
        closeDialog.setSize(new java.awt.Dimension(400, 125));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("Do you want to save");

        saveButton1.setText("Save");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });

        dontSaveButton1.setText("Don't save");
        dontSaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontSaveButton1ActionPerformed(evt);
            }
        });

        cancelButton1.setText("Cancel");
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout closeDialogLayout = new javax.swing.GroupLayout(closeDialog.getContentPane());
        closeDialog.getContentPane().setLayout(closeDialogLayout);
        closeDialogLayout.setHorizontalGroup(
            closeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(closeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(closeDialogLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(closeDialogLayout.createSequentialGroup()
                        .addComponent(saveButton1)
                        .addGap(87, 87, 87)
                        .addComponent(dontSaveButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        closeDialogLayout.setVerticalGroup(
            closeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(closeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton1)
                    .addComponent(dontSaveButton1)
                    .addComponent(cancelButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My simple notepad");
        setPreferredSize(new java.awt.Dimension(875, 550));
        setResizable(false);

        editor.setColumns(20);
        editor.setRows(5);
        editor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(editor);

        File.setText("File");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        File.add(open);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        File.add(save);

        close.setText("Close");
        File.add(close);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        File.add(exit);

        menu.add(File);

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        copyMenu.setText("Copy");
        copyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuActionPerformed(evt);
            }
        });
        Edit.add(copyMenu);

        cutMenu.setText("Cut");
        cutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuActionPerformed(evt);
            }
        });
        Edit.add(cutMenu);

        pasteMenu.setText("Paste");
        pasteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuActionPerformed(evt);
            }
        });
        Edit.add(pasteMenu);

        selectAllMenu.setText("Select All");
        selectAllMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllMenuActionPerformed(evt);
            }
        });
        Edit.add(selectAllMenu);

        menu.add(Edit);

        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        aboutApp.setText("About");
        aboutApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutAppActionPerformed(evt);
            }
        });
        Help.add(aboutApp);

        menu.add(Help);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        openFile();
    }//GEN-LAST:event_openActionPerformed

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_FileActionPerformed

    private void aboutAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutAppActionPerformed
        // TODO add your handling code here:
        aboutForm.setVisible(true);
    }//GEN-LAST:event_aboutAppActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HelpActionPerformed

    private void copyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuActionPerformed
        // TODO add your handling code here:
        copyFromTextArea();
    }//GEN-LAST:event_copyMenuActionPerformed

    private void cutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuActionPerformed
        // TODO add your handling code here:
        cutFromTextArea();
    }//GEN-LAST:event_cutMenuActionPerformed

    private void pasteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuActionPerformed
        // TODO add your handling code here:
        pasteFromTextArea();
    }//GEN-LAST:event_pasteMenuActionPerformed

    private void editorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editorMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editorMouseClicked

    private void editorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editorMousePressed
        // TODO add your handling code here:  
        editor.setComponentPopupMenu(menu2);
    }//GEN-LAST:event_editorMousePressed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EditActionPerformed

    private void selectAllMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllMenuActionPerformed
        // TODO add your handling code here:
        selectAllFromTextArea();
    }//GEN-LAST:event_selectAllMenuActionPerformed

    private void selectAllMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllMenu2ActionPerformed
        // TODO add your handling code here:
        selectAllFromTextArea();
    }//GEN-LAST:event_selectAllMenu2ActionPerformed

    private void pasteMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenu2ActionPerformed
        // TODO add your handling code here:
        pasteFromTextArea();
    }//GEN-LAST:event_pasteMenu2ActionPerformed

    private void cutMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenu2ActionPerformed
        // TODO add your handling code here:
        cutFromTextArea();
    }//GEN-LAST:event_cutMenu2ActionPerformed

    private void copyMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenu2ActionPerformed
        // TODO add your handling code here:
        copyFromTextArea();
    }//GEN-LAST:event_copyMenu2ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_exitActionPerformed

    private void dontSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontSaveButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_dontSaveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        exitDialog.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void dontSaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontSaveButton1ActionPerformed
        // TODO add your handling code here:
        path = null;
        editor.setText(null);
        text = null;
    }//GEN-LAST:event_dontSaveButton1ActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        // TODO add your handling code here:
        closeDialog.setVisible(false);
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        saveFile();
    }//GEN-LAST:event_saveActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
        saveFile();
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        saveFile();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleNotePad().setVisible(true);
            }
        });
    }
    
    private void openFile(){
    text = null;    
    choose = new JFileChooser();
    filter = new FileNameExtensionFilter(
        "text files only", "txt");
    choose.setFileFilter(filter);
    int returnVal = choose.showOpenDialog(chooser);
    if(returnVal == JFileChooser.APPROVE_OPTION) {
        path = choose.getSelectedFile().getPath();
        setTitle(getTitle() + " - " + path);
    }
        try {
           
        fileRead = new FileReader(path);
        fileIn = new BufferedReader(fileRead);
            while((x=fileIn.readLine())!=null){
               text = text + x + System.lineSeparator();
            }
            editor.setText(text);
            fileIn.close();
            fileRead.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SimpleNotePad.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SimpleNotePad.class.getName()).log(Level.SEVERE, null, ex);
        }
     }  
    
    
    
    private void saveFile(){
       if (path != null){   
            try {
                fileWrite = new FileWriter(path);
                fileWrite.write(editor.getText());
                fileWrite.close();
                text = editor.getText();
            } catch (IOException ex) {
                Logger.getLogger(SimpleNotePad.class.getName()).log(Level.SEVERE, null, ex);
            } 
        } else {
            choose = new JFileChooser();
            filter = new FileNameExtensionFilter(
                "text files only", "txt");
            choose.setFileFilter(filter);
            int returnVal = choose.showSaveDialog(chooser);
            if(returnVal == JFileChooser.APPROVE_OPTION) {
            path = choose.getSelectedFile().getPath();
            setTitle(getTitle() + " - " + path);
           try {
                fileWrite = new FileWriter(path);
                fileWrite.write(editor.getText());
                fileWrite.close();
                text = editor.getText();
            } catch (IOException ex) {
                Logger.getLogger(SimpleNotePad.class.getName()).log(Level.SEVERE, null, ex);
            } 
       }
       }
       } 

    private void copyFromTextArea(){
        editor.copy();
    }
    
    private void cutFromTextArea(){
        editor.cut();
    }
     
    private void pasteFromTextArea(){
        editor.paste();
    }
    
    private void selectAllFromTextArea(){
        editor.selectAll();
    }
     
    public void exit(){
      if (path == null && editor.getText().isEmpty()){
          System.exit(0);
      } else if (path != null && editor.getText().equals(text)){
          System.exit(0);
      } else {
            exitDialog.setVisible(true);
      }
    }
    
     public void close(){
      if (path == null && editor.getText().isEmpty()){
          setTitle("My simple notepad");
      } else if (path != null && editor.getText().equals(text)){
          setTitle("My simple notepad");
      } else {
            closeDialog.setVisible(true);
      }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem aboutApp;
    private javax.swing.JFrame aboutForm;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JMenuItem close;
    private javax.swing.JDialog closeDialog;
    private javax.swing.JMenuItem copyMenu;
    private javax.swing.JMenuItem copyMenu2;
    private javax.swing.JMenuItem cutMenu;
    private javax.swing.JMenuItem cutMenu2;
    private javax.swing.JButton dontSaveButton;
    private javax.swing.JButton dontSaveButton1;
    private javax.swing.JTextArea editor;
    private javax.swing.JMenuItem exit;
    private javax.swing.JDialog exitDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPopupMenu menu2;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem pasteMenu;
    private javax.swing.JMenuItem pasteMenu2;
    private javax.swing.JMenuItem save;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveButton1;
    private javax.swing.JMenuItem selectAllMenu;
    private javax.swing.JMenuItem selectAllMenu2;
    // End of variables declaration//GEN-END:variables
}
